### ISSUE TITLE
Use docker:stable not docker:latest in your Dockerfile

### ISSUE THREAD

**Issue by matthewadams** [ezkrg/docker-buildx#1]

**Comment by ezkrg** [comment]
docker:stable is not a maintained tag anymore, it has been updated 2 years ago.

```bash
$ docker run -it --rm docker:stable docker -v  
Docker version 19.03.14, build 5eb3275
```

 docker:20-cli and docker:cli contain buildx plugin now. this image created before docker add it to the official images.

**Comment by matthewadams** [comment]
oh man
